services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        NODE_ENV: local
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NODE_ENV: local
    ports:
      - "${FRONTEND_PORT}:4173"
    depends_on:
      - backend
    networks:
      - app-network
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3005:3000"
    networks:
      - app-network
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
